import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { appRunning, bridgeProblem, bridgeRunning, parseProcessList } from '../core/running.js';
import { loadSettings } from '../core/settings.js';

const procs = [
  { name: 'Claude.exe', path: 'C:\\Program Files\\WindowsApps\\Claude_0.13.5_x64__pzs8sxrjxfjjc\\app\\Claude.exe', commandLine: '"C:\\Program Files\\WindowsApps\\Claude_0.13.5_x64__pzs8sxrjxfjjc\\app\\Claude.exe"' },
  { name: 'claude.exe', path: 'X:\\profiles\\person\\.local\\bin\\claude.exe', commandLine: 'claude -p "hello"' },
  { name: 'T3 Code.exe', path: 'X:\\profiles\\person\\AppData\\Local\\Programs\\T3 Code\\T3 Code.exe', commandLine: null },
  { name: 'node.exe', path: 'C:\\Program Files\\nodejs\\node.exe', commandLine: 'node X:\\profiles\\person\\claude-slack-bridge\\server.js --port 3000' },
  { name: 'svchost.exe', path: null, commandLine: null },
];

test('the process list parser accepts a list, a single object, and refuses junk', () => {
  const many = parseProcessList('[{"Name":"a.exe","ExecutablePath":"C:\\\\a.exe","CommandLine":"a"},{"Name":"b.exe"}]');
  assert.equal(many.length, 2);
  assert.deepEqual(many[1], { name: 'b.exe', path: null, commandLine: null });
  assert.deepEqual(parseProcessList('{"Name":"only.exe","ExecutablePath":null,"CommandLine":null}'),
    [{ name: 'only.exe', path: null, commandLine: null }]);
  assert.deepEqual(parseProcessList('not json'), []);
  assert.deepEqual(parseProcessList(''), []);
});

test('an app with a known program file matches on that path, whatever the case or slashes', () => {
  assert.equal(appRunning(procs, { exePath: 'x:/profiles/person/appdata/local/programs/t3 code/T3 CODE.EXE' }), true);
  assert.equal(appRunning(procs, { exePath: 'C:\\somewhere\\else\\T3 Code.exe' }), false);
});

test('a Store app matches on its package folder, so the claude CLI never lights the Claude Desktop dot', () => {
  const claudeDesktop = { appId: 'Claude_pzs8sxrjxfjjc!Claude' };
  assert.equal(appRunning(procs, claudeDesktop), true);
  // Same exe name, different publisher hash: someone else's package, not this app.
  assert.equal(appRunning([procs[1]], claudeDesktop), false);
  assert.equal(appRunning([{ name: 'Claude.exe', path: 'C:\\Program Files\\WindowsApps\\Claude_1.0_x64__otherhash\\app\\Claude.exe' }], claudeDesktop), false);
});

test('a custom launcher whose Start-menu id is a program path matches on it; anything else is honestly unknown', () => {
  assert.equal(appRunning(procs, { appId: 'X:\\profiles\\person\\AppData\\Local\\Programs\\T3 Code\\T3 Code.exe' }), true);
  assert.equal(appRunning(procs, { appId: 'C:\\nowhere\\gone.exe' }), false);
  assert.equal(appRunning(procs, { appId: 'Microsoft.AutoGenerated.{ABC}' }), null);
  assert.equal(appRunning(procs, {}), null);
});

test('a bridge matches by command-line text, case-insensitively, and an empty match never matches', () => {
  assert.equal(bridgeRunning(procs, 'Claude-Slack-Bridge'), true);
  assert.equal(bridgeRunning(procs, 'some-other-bridge'), false);
  assert.equal(bridgeRunning(procs, ''), false);
  assert.equal(bridgeRunning(procs, null), false);
});

test('bridge entries are validated before they are saved', () => {
  assert.equal(bridgeProblem({ label: 'Slack bridge', match: 'claude-slack-bridge' }), null);
  assert.ok(bridgeProblem({ label: '', match: 'claude-slack-bridge' }));
  assert.ok(bridgeProblem({ label: 'Slack bridge', match: '  ' }));
  assert.ok(bridgeProblem({ label: 'Slack bridge', match: 'ab' }), 'two characters would match half the machine');
  assert.ok(bridgeProblem({ label: 'Slack bridge', match: 'a\nb' }));
  assert.ok(bridgeProblem({}));
});

test('settings default bridges to an empty list and drop malformed entries', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sb-running-'));
  const file = path.join(dir, 'settings.json');
  assert.deepEqual(loadSettings(file).bridges, []);
  fs.writeFileSync(file, JSON.stringify({ bridges: [
    { id: 'bridge-1', label: 'Slack bridge', match: 'claude-slack-bridge' },
    { id: 42, label: 'broken', match: 'x' },
    'junk',
    null,
  ] }));
  assert.deepEqual(loadSettings(file).bridges, [{ id: 'bridge-1', label: 'Slack bridge', match: 'claude-slack-bridge' }]);
  fs.rmSync(dir, { recursive: true, force: true });
});

// The bridge row's wording lives in the single-file UI; lift it the way ui-apps.test.js does.
const HTML = fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'ui', 'index.html'), 'utf8');
function lift(name) {
  const lines = HTML.split('\n');
  const start = lines.findIndex((l) => l.startsWith(`function ${name}(`));
  assert.ok(start >= 0, `found ${name} in index.html`);
  const end = lines.findIndex((l, i) => i > start && l === '}');
  assert.ok(end > start, `found the end of ${name}`);
  return lines.slice(start, end + 1).join('\n');
}
const bridgeStateView = new Function(`${lift('bridgeStateView')}\nreturn bridgeStateView;`)();

test('a bridge row says Running, Not running, or State unknown, and only Running is green', () => {
  assert.deepEqual(bridgeStateView(true), { text: 'Running', cls: 'runstate' });
  assert.deepEqual(bridgeStateView(false), { text: 'Not running', cls: 'runstate off' });
  assert.deepEqual(bridgeStateView(null), { text: 'State unknown', cls: 'runstate off' });
});
