const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sb', {
  state: () => ipcRenderer.invoke('sb:state'),
  setActive: (id) => ipcRenderer.invoke('sb:setActive', id),
  addAccount: (provider) => ipcRenderer.invoke('sb:addAccount', provider),
  removeAccount: (id) => ipcRenderer.invoke('sb:removeAccount', id),
  rename: (id, label) => ipcRenderer.invoke('sb:rename', id, label),
  providers: () => ipcRenderer.invoke('sb:providers'),
  install: (toolId, mode) => ipcRenderer.invoke('sb:install', toolId, mode),
  doctor: () => ipcRenderer.invoke('sb:doctor'),
  updates: () => ipcRenderer.invoke('sb:updates'),
  detectOne: (toolId) => ipcRenderer.invoke('sb:detectOne', toolId),
  candidates: () => ipcRenderer.invoke('sb:candidates'),
  register: (candidate) => ipcRenderer.invoke('sb:register', candidate),
  fix: (action, args) => ipcRenderer.invoke('sb:fix', action, args),
  signin: (accountId) => ipcRenderer.invoke('sb:signin', accountId),
  quota: (accountId) => ipcRenderer.invoke('sb:quota', accountId),
  setUsageSource: (accountId) => ipcRenderer.invoke('sb:setUsageSource', accountId),
  openExternal: (url) => ipcRenderer.invoke('sb:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('sb:openPath', p),
  apps: () => ipcRenderer.invoke('sb:apps'),
  setAppOrder: (ids) => ipcRenderer.invoke('sb:setAppOrder', ids),
  antigravity: () => ipcRenderer.invoke('sb:antigravity'),
  presence: () => ipcRenderer.invoke('sb:presence'),
  appLaunch: (id) => ipcRenderer.invoke('sb:appLaunch', id),
  appInstall: (id, mode) => ipcRenderer.invoke('sb:appInstall', id, mode),
  startAppsList: () => ipcRenderer.invoke('sb:startAppsList'),
  addCustomApp: (entry) => ipcRenderer.invoke('sb:addCustomApp', entry),
  removeCustomApp: (appId) => ipcRenderer.invoke('sb:removeCustomApp', appId),
  openTerminal: (bin) => ipcRenderer.invoke('sb:openTerminal', bin),
  updateCheck: () => ipcRenderer.invoke('sb:updateCheck'),
  updateRun: (tag, assetUrl) => ipcRenderer.invoke('sb:updateRun', tag, assetUrl),
  getUpdateRepo: () => ipcRenderer.invoke('sb:getUpdateRepo'),
  setUpdateRepo: (slug) => ipcRenderer.invoke('sb:setUpdateRepo', slug),
  onUpdateAvailable: (cb) => ipcRenderer.on('sb:updateAvailable', (_e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('sb:updateProgress', (_e, p) => cb(p)),
  onRefresh: (cb) => ipcRenderer.on('sb:refresh', cb),
  onNavigate: (cb) => ipcRenderer.on('sb:navigate', (_e, hash) => cb(hash)),
});
