const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sb', {
  state: (forceAuthAccountId = null) => ipcRenderer.invoke('sb:state', forceAuthAccountId),
  configExport: () => ipcRenderer.invoke('sb:configExport'),
  configImport: () => ipcRenderer.invoke('sb:configImport'),
  setActive: (id) => ipcRenderer.invoke('sb:setActive', id),
  addAccount: (provider) => ipcRenderer.invoke('sb:addAccount', provider),
  removeAccount: (id) => ipcRenderer.invoke('sb:removeAccount', id),
  rename: (id, label) => ipcRenderer.invoke('sb:rename', id, label),
  providers: () => ipcRenderer.invoke('sb:providers'),
  install: (toolId, mode) => ipcRenderer.invoke('sb:install', toolId, mode),
  doctor: () => ipcRenderer.invoke('sb:doctor'),
  providerHealth: (force = false) => ipcRenderer.invoke('sb:providerHealth', force),
  updates: () => ipcRenderer.invoke('sb:updates'),
  detectOne: (toolId) => ipcRenderer.invoke('sb:detectOne', toolId),
  candidates: () => ipcRenderer.invoke('sb:candidates'),
  register: (candidate) => ipcRenderer.invoke('sb:register', candidate),
  fix: (action, args) => ipcRenderer.invoke('sb:fix', action, args),
  signin: (accountId) => ipcRenderer.invoke('sb:signin', accountId),
  quota: (accountId, force = false) => ipcRenderer.invoke('sb:quota', accountId, force),
  setUsageSource: (accountId) => ipcRenderer.invoke('sb:setUsageSource', accountId),
  openExternal: (url) => ipcRenderer.invoke('sb:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('sb:openPath', p),
  apps: () => ipcRenderer.invoke('sb:apps'),
  setAppOrder: (ids) => ipcRenderer.invoke('sb:setAppOrder', ids),
  antigravity: () => ipcRenderer.invoke('sb:antigravity'),
  presence: () => ipcRenderer.invoke('sb:presence'),
  appLaunch: (id, profileDir = null) => ipcRenderer.invoke('sb:appLaunch', id, profileDir),
  appProfiles: (id) => ipcRenderer.invoke('sb:appProfiles', id),
  addAppProfile: (id) => ipcRenderer.invoke('sb:addAppProfile', id),
  removeAppProfile: (id, dir) => ipcRenderer.invoke('sb:removeAppProfile', id, dir),
  appInstall: (id, mode) => ipcRenderer.invoke('sb:appInstall', id, mode),
  startAppsList: () => ipcRenderer.invoke('sb:startAppsList'),
  addCustomApp: (entry) => ipcRenderer.invoke('sb:addCustomApp', entry),
  removeCustomApp: (appId) => ipcRenderer.invoke('sb:removeCustomApp', appId),
  running: () => ipcRenderer.invoke('sb:running'),
  bridges: () => ipcRenderer.invoke('sb:bridges'),
  addBridge: (entry) => ipcRenderer.invoke('sb:addBridge', entry),
  removeBridge: (id) => ipcRenderer.invoke('sb:removeBridge', id),
  terminals: () => ipcRenderer.invoke('sb:terminals'),
  openTerminal: (bin, accountId) => ipcRenderer.invoke('sb:openTerminal', bin, accountId ?? null),
  mcpState: () => ipcRenderer.invoke('sb:mcpState'),
  mcpBrowse: (opts) => ipcRenderer.invoke('sb:mcpBrowse', opts ?? {}),
  mcpAdd: (entry) => ipcRenderer.invoke('sb:mcpAdd', entry),
  mcpRemove: (name) => ipcRenderer.invoke('sb:mcpRemove', name),
  mcpRegister: (clientId, name) => ipcRenderer.invoke('sb:mcpRegister', clientId, name),
  mcpUnregister: (clientId, name) => ipcRenderer.invoke('sb:mcpUnregister', clientId, name),
  mcpList: (clientId) => ipcRenderer.invoke('sb:mcpList', clientId),
  updateCheck: () => ipcRenderer.invoke('sb:updateCheck'),
  updateRun: (tag, assetUrl) => ipcRenderer.invoke('sb:updateRun', tag, assetUrl),
  getUpdateRepo: () => ipcRenderer.invoke('sb:getUpdateRepo'),
  setUpdateRepo: (slug) => ipcRenderer.invoke('sb:setUpdateRepo', slug),
  getLanes: () => ipcRenderer.invoke('sb:getLanes'),
  addLane: (lane) => ipcRenderer.invoke('sb:addLane', lane),
  removeLane: (laneId) => ipcRenderer.invoke('sb:removeLane', laneId),
  updateLaneOrder: (laneIds) => ipcRenderer.invoke('sb:updateLaneOrder', laneIds),
  setLaneBudget: (laneId, budget) => ipcRenderer.invoke('sb:setLaneBudget', laneId, budget),
  onUpdateAvailable: (cb) => ipcRenderer.on('sb:updateAvailable', (_e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('sb:updateProgress', (_e, p) => cb(p)),
  onRefresh: (cb) => ipcRenderer.on('sb:refresh', cb),
  onNavigate: (cb) => ipcRenderer.on('sb:navigate', (_e, hash) => cb(hash)),
});
